### ISSUE TITLE
Migrate docker images to Ubuntu 22.04

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/docker-deployment-images#14]
Probably this issue will be split in single issues.

For sure we need to port:

- [x] Port superbuild
- [x] Port superbuild-icubhead
- [x] Port superbuild-icubhead-withuser
- [x] Fix `superbuild-ros1` that can be eventually deprecated
- [x] Fix `superbuild-ros2` that can be kept as useful for the close future
- [x] `superbuild-nvidia` cannot be updated to ubuntu 22.04 since latest version of the image it needs as starting image is: `nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04`
- [x] `superbuild-pytorch` can be updated to 22.04 with starting image `anibali/pytorch:2.0.1-cuda11.8-ubuntu22.04`
- [x] `tensorflow` can be updated as well
- [x] All the rest is updated
- [x] Delete or fix images which are constantly failing due to various reason
    - [x] Deletd `open-face` and `human-sensing` under `demos` folder 
- [x] (Optional) if no issues generate, upgrade to 22.04 all remaining images too.

**DoD**
All the images are based on Ubuntu 22.04

**Comment by MSECode** [comment]
I've updated all the working images to use ubuntu 22.04 `jammy-jellyfish` as `START_IMG`, fix `superbuild-ros2` image that can be useful for the upcoming developments and removed images that can be considered as deprecated since the repo they used as not updated from around 2019-2020, such as `open-face` and `human-sensing`.
If you can take a look to the latest commits, @valegagge, I would do a squash, commit on the official repo, check compilation and open PR

**Comment by MSECode** [comment]
PR opened to main repository

https://github.com/icub-tech-iit/docker-deployment-images/pull/17

In PR body can be checked the changes introduced.

cc: @valegagge

**Comment by valegagge** [comment]
As discussed F2F, the changes are ok. 
In order to improve the maintenance and to test future changes on a fork, we could open an issue where write down some ideas for the improvements.

**Comment by valegagge** [comment]
#17 merged!

cc @MSECode

**Comment by MSECode** [comment]
I'll checking the images that failed to build. For superbuild-icubhead is just due to the binaries, where I need to check the `Dockerfile4Production` file.
Then, we have errors with the libraries in superbuild-gazebo which should be built only with Ubuntu 20.04 for now, since the library gazebo11 has not been available in the `osrfoundation` for Ubuntu 22.04, as specified in a note in the official gazebo documentation.
Lastly, pythorc has still some issue in building due to python3
I'll try to find a solution otherwise we can drop it since it not used by anyone.

**Comment by valegagge** [comment]
After the meeting with Silo-Sw, we decided to maintain only the image that we need, so `superbuild`, `superbuild-icubhead` and `superbuild-icubhead-with user`.
So we can fix the  `Dockerfile4Production` file of superbuild-icubhead only.

**Some notes about gazebo image**

Gazebo image is based on superbuild, now compiled with 22.04 ubuntu.
As [Gazebo documentation](https://classic.gazebosim.org/tutorials?tut=install_ubuntu) says, the binary package is unavailable for 22.04 Ubuntu version. 
So we need to update its dockerfile compiling gazebo from the source. We have decided to postpone this activity when we'll need it.

Also the pythorch image will be removed because no one use it.

Anyway before proceeding to remove the image we have to do a poll.

**Comment by MSECode** [comment]
PR opens here: https://github.com/icub-tech-iit/docker-deployment-images/pull/18

**Comment by MSECode** [comment]
After compilation of PR: #18 , there are still some image failing due to not correct source images and old library versions. I'm fixing them and pasting here the corrections:
- `funny-things` has old node and npm version, which are deprecated for ubuntu 22. Here the screen of the image compiled locally:

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/1ce20fb0-e761-4afe-912c-847dbba5adbb)

- `ros2` had an error in the image used as **START_IMG** for the build
- `ros1` same error -> here need to use a specific older version of the superbuild-icubhead built using as START_IMG ubuntu:focal
- `superbuild-google` has an error in the tag used in a third party library. Now correct

**Comment by valegagge** [comment]
Hi @MSECode, I suppose that you just forgot to upload the fix of `superbuild-google` and it works fine! 😺

**Comment by MSECode** [comment]
> Hi @MSECode, I suppose that you just forgot to upload the fix of `superbuild-google` and it works fine! 😺

Yes, just the screen but I've checked the code also for that image. I forgot to upload the screen at the end. It took a lot to complete the build and I missed to take the screen before closing the terminal

**Comment by MSECode** [comment]
Fixed some images that do not need to be deprecated. It was due to third party libraries that just need to be updated:
- superbuild-tensorflow-cpu
    - source
    
![MicrosoftTeams-image (12)](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/7c341fc9-af99-461f-a31f-79111239ffa4)

    - binaries
    
![MicrosoftTeams-image (11)](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/2a56319d-c8bb-4c1f-9a78-bf7f1dd0a7d0)

- superbuild-tensorflow-gpu
    - source
    
![MicrosoftTeams-image (10)](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/397bc43d-6946-4b04-aac2-0280433a3f63)

    - binaries
    
![MicrosoftTeams-image (13)](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/20b47269-bf94-46ba-b82e-99dd30f2dee6)

- superbuild-pytorch
    - source
    
![MicrosoftTeams-image (14)](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/77c6967c-4d11-4098-86b8-ce98e2df63e8)

    - binaries 
    
   
![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/77933235/b3480abc-f4d1-4f73-ae75-ff35db4ef880)

**Comment by valegagge** [comment]
Hi @MSECode ,
I noticed this error in the compilation of ROS2.

![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/4233231/d4fbe50a-abac-432b-8a25-08e029059685)

It seems that we give the wrong source image: `superbuild-icubhead:master-sources` doesn't exist.
![image](https://github.com/icub-tech-iit/docker-deployment-images/assets/4233231/95e292e7-04e0-4f90-8156-c9561a26f9de)

Can you check it?
Thank you!

**Comment by valegagge** [comment]
Hi @MSECode ,

regarding the google and speech images, I suggest moving them in the deprecated folder because they still have some compilation issues.

What di you think?

**Comment by MSECode** [comment]
Yeh,
I've checked that as well and it makes sense to deprecate them.
The others seems fine to me.

**Comment by valegagge** [comment]
Hi @MSECode ,

> can we close the issue and do the announcement and poll if someone would use them?

Yes of course!
